### ISSUE TITLE
Падает вот тут

### ISSUE THREAD

**Issue by Evgueni-Petrov-aka-espetrov** [Evgueni-Petrov-aka-espetrov/17202#1]
https://github.com/Evgueni-Petrov-aka-espetrov/17202/blob/e37eb44af6093c976c3a336eeb99da2b299ecb18/%D0%9C%D0%BE%D0%BA%D1%80%D0%BE%D1%83%D1%81%D0%BE%D0%B2/prog30.c#L60

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Это для Антона )

**Comment by amokrousov** [comment]
Исправил, теперь в студии не падает
