### ISSUE TITLE
разве недостаточно условия в строке 22?

### ISSUE THREAD

**Issue by Evgueni-Petrov-aka-espetrov** [Evgueni-Petrov-aka-espetrov/17202#16]
https://github.com/Evgueni-Petrov-aka-espetrov/17202/blob/92e9774967454e9e9a1aa61868ff591d173a4821/Smal/Lab0/lab_0.c#L19

**Comment by YpbIrb** [comment]
В 22 строке идет проверка на то, что запятая одна, а тут проверка на то, что она не стоит на первом или последнем месте

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
А, виноват.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Перейдите с utf-16 на utf-8, пожалуйста.

9 октября 2017 г., 19:43 пользователь Smal_Ivan <notifications@github.com>
написал:

**Comment by YpbIrb** [comment]
Наконец-то получилось

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Ура! :)

2017-10-09 23:53 GMT+07:00 Smal_Ivan <notifications@github.com>:
