### ISSUE TITLE
Как сделать, чтобы лабораторная 5 проходила ограничение по размеру архива?

### ISSUE THREAD

**Issue by amokrousov** [Evgueni-Petrov-aka-espetrov/17202#22]
Как Вы и сказали, сделал сохранение дерева Хаффмана через битовые поля (1 - ветвь, 0 - поле), размер таблицы до 320 байт (10 бит на символ), тем не менее 29 тест всё равно не проходится. Что делать?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Убрать лишние 4 байта -- вроде разобрались уже.
